class Color(DefaultColor):
    USERNAME_FG = 17
    USERNAME_BG = 226

    HOSTNAME_FG = 0
    HOSTNAME_BG = 214

    HOME_SPECIAL_DISPLAY = False
    PATH_BG = 234
    PATH_FG = 48
    CWD_FG = 15
    SEPARATOR_FG = 48

    READONLY_BG = 200
    READONLY_FG = 15

    REPO_CLEAN_BG = 214
    REPO_CLEAN_FG = 17
    REPO_DIRTY_BG = 226
    REPO_DIRTY_FG = 17

    JOBS_FG = 15
    JOBS_BG = 200

    CMD_PASSED_BG = 237
    CMD_PASSED_FG = 15
    CMD_FAILED_BG = 52
    CMD_FAILED_FG = 15

    SVN_CHANGES_BG = REPO_DIRTY_BG
    SVN_CHANGES_FG = REPO_DIRTY_FG

    VIRTUAL_ENV_BG = 45
    VIRTUAL_ENV_FG = 0

